apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "yogstation-cloudbeaver.fullname" . }}
  labels:
    {{- include "yogstation-cloudbeaver.labels" . | nindent 4 }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: {{ .Values.storage.storageClassName }}
